name: Standalone CLI
on: [push, pull_request]
jobs:
   machineStandalone:
    name: Run skims scan on machine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Run skims scan
        uses: docker://docker.io/fluidattacks/skims:latest
        with:
             args: skims --strict scan .

